#ttttt
name: Build-Scan-Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BuildNumber: ${{ github.run_id }}-${{ github.run_number }}
  ImageName: 'liamgu/container-scanning-demo'

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps:
     
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        
        username: ${{ secrets.DockerHubUser }} 
        password: ${{ secrets.DockerHubPassword }}
        repository: ${{ env.ImageName }}
        tags: 'github-${{ env.BuildNumber }}'
        dockerfile: 'Dockerfile'
        push: false
    - name: Trivy Scan - Unknown, Low and Medium Severity
      uses: aquasecurity/trivy-action@0.16.1
      with:
        image-ref: ${{ env.ImageName }}:github-${{ env.BuildNumber }}  
        exit-code: 0
        severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL 
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
